### ISSUE TITLE
Question about paper

### ISSUE THREAD

**Issue by Y-T-G** [lyumengyao/blad#3]
Hello. Great work.

I have a question about a part in the paper.

![image](https://github.com/lyumengyao/blad/assets/32206511/c09305de-5831-49c7-ad16-3d68ddb54296)

I am finding it difficult to understand this. How is are boxes fed into the regression branch of the chairman model? What do boxes mean here? Are they the cropped versions of the images?

**Comment by lyumengyao** [comment]
Hi Y-T-G, thank you for your interest and sorry for the confusion and late reply. 
The candidate boxes mentioned here refer to the prediction results from M members. They can be simply understood as cropped images being forwarded through the localization head. But actually, in implementation, it is the coordinates of the bbox that are inversely transformed and then forwarded to the roi_head for reference. L574 and L701 of mixed_teacher.py would be helpful for understanding. 
Feel free to reopen the issue if it hasn't completely addressed your question.
